### PR TITLE
Use `gh‑pages` branch

### PR DESCRIPTION
**Pull request by ExE-Boss**
This makes the build result be deployed to the `gh‑pages` branch.

---

The configuration is based on <https://github.com/tc39/proposal-realms/blob/master/.github/workflows/publish.yml>

### CODE REVIEW

**Comment by ljharb** [comment]
Why is this an improvement? It's simpler imo when there's only a single branch for the raw and rendered spec.

**Comment by ExE-Boss** [comment]
It ensures that the `master` branch only contains the source files.

**Comment by ljharb** [comment]
Right, but I find that more complex than having one branch for the entire proposal repo.

**Comment by gibson042** [comment]
I strongly agree with @ljharb about keeping all contents in a single branch, but would personally prefer use of /docs rather than dumping rendered output at the top level.

**Comment by ljharb** [comment]
Closed by #32.

**Pull request closed without merging**
